samtools_markdup:
  input:
    sorted_bam: "data/02_alignment/post_alignment/samtools/sort/output/"
  output:
    markdup_bam: "data/02_alignment/post_alignment/samtools/markdup/output/"
  params:
    threads:
      default: 2
    remove_duplicates: false
    
