macs_callpeak:
  input:
    markdup_bam: "data/02_alignment/post_alignment/samtools/markdup/output"
  output: 
    peaks: "data/04_peak_calling/macs/output/"
  params:
    genome_size: "hs"
    qvalue: 0.01
    nomodel: true #Skip MACS2's model-basaed fragment length estimation 
    shift: -100
    extsize: 200
    format: "BAM"
    threads:
      default: 2























#Mamba: drop-in replacement for conda, writte n in c++.
#Faster dependency resolution: uses libsolv backened, which is highly efficient.
#Parallel downloading .
