diffbind:
  input: 
    sample_sheet: "data/04_peak_calling/diffbind/input/sample_sheet.csv"
  output: 
    results_dir: "data/04_peak_calling/diffbind/output/"
  params:
    reference: "hg38"
    threads:
      default: 2
    contrast_column: "condition"
    
    
