genrich:
  input:
    markdup_bam: "data/02_alignment/post_alignment/samtools/markdup/"
  output:
    bed_peak: "data/04_peak_calling/genrich/output/"
  params:
    threads:
      default: 2 #Assuming that the user has atleast dual core CPU(Central Processing Unit).
      
#Skip -r option which is for removing mitochondrial reads as this task has already been done by samtools. 
#Logically consistent. 



