picard_collect_insert_size_metrics:
  input:
    bam_sorted: "data/02_alignment/samtools/sort/input/"
  output:
    metrics: "data/02_alignment/picard_metrics/collect_insert_size_metrics/output/"
    histogram: "data/02_alignment/picard_metrics/collect_insert_size_metrics/output/"
  params:
    threads: 
      deafult: 2
    M: 0.5
    validation_stringency: LENIENT
    
    
