phantompeakqualtools:
  input:
    markdup: "data/02_alignment/post_alignment/samtools/markdup/output/"
  output:
    qc_metrics: "data/03_quality_control/phantompeakqualtools/output/"
  params:
    threads:
      default: 2
    
