qualimap_bamqc:
  input:
    markdup_bam: "data/02_alignment/post_alignment/samtools/markdup/output"
  output:
    html: "data/03_quality_control/qualimap/output/"
    pdf: "data/03_quality_control/qualimap/output/"
  params:
    threads:
      default: 2
      
