bwa: 
  input: 
    R1_fastp: "data/01_preprocessing/fastp/output/"
    R2_fastp: "data/01_preprocessing/fastp/output/"
  output: 
    sam: "data/02_alignment/bwa/output/"
  params: 
    threads: 
      default: 2 #Assuming that the user has atleast dual core CPU 
     index: "data/02_alignment/bwa/index/genome.fa"
      
    
