clusterprofiler:
  input:
    gene_list: "data/05_analysis/clusterprofiler/input/"
  output:
    enrichment_result: "data/05_analysis/clusterprofiler/output/"
  params:
    orgdb: "org.Hs.eg.db"
    keytype: "ENTREZID"
    ont: "BP"
    pAdjustMethod: "BH"
    qvalueCutOff: 0.05
    readable: TRUE
    threads:
      default: 2
    csv:
      file: "go_enrichment_result.csv"  
      
      
#Config.yaml is a  conda configuration file in which inputs and #outputs paths are configured, parameters  and other settings are #configured. To configure means to create a variable(known as #key) and assign the value to it . The  value can be accessed #using the syntax config["key"] in the key. When the value #changed , the rule will react to it making the parameter #dynamic.  The file provides a central location to configure all #the dynamic pieces. The values are provided as key-value #pairs(dict form). Check. Put a tick mark at the end of each #line       
#Separation of concerns: The dynamic values are configured in a separate yaml file and the rule that will use the values is in different file(.smk).
#The pipeline is clean. 
#The pipeline is easy to maintain.The new value can replace  #the old value without  neing involved with  the rule. The #logical flow of the rule remains intact.
#Easy to share.  
#Easy to read.
