igvtools:
  input:
    bam: "data/02_alignment/post_alignment/samtools/view/output/"
  output:
    tdf: "data/06_visualization/igvtools/output/"
  params:
    genome: "hg38"
    window_size: 25 
    smooth_factor: 5
    threads:
      default: 2
