homer:
  input:
    bed_dir: "data/02_peak_calling/macs/output/"
  output:
     motif_dir: "data/05_analysis/homer/output/"
  params:
    threads: 
      default: 2
    genome: "hg38"
    size: "given"
