multiqc:
  input:
    fastp: "data/01_preprocessing/fastp/output/"
    fastqc: "data/01_preprocessing/fastqc/output/"
    mitoATAC: "data/01_preprocessing/mitoATAC/output/"
  output: "data/01_preprocessing/multiqc/"
  params:
    threads:
    default: 2  
   
      
     
