#!/bin/bash

mkdir results

dirs=(
"benchmarks/bedtools_genomecov"
"logs/bedtools_genomecov"
"benchmarks/tss_enrichment"
"logs/tss_enrichment"
"benchmarks/tn5_shift"
"logs/tn5_shift"
"benchmarks/sorted_bedgraph"
"logs/sorted_bedgraph"
"benchmarks/samtools_view"
"logs/samtools_view"
"benchmarks/samtools_stats"
"logs/samtools_stats"
"benchmarks/samtools_sort"
"logs/samtools_sort"
"benchmarks/samtools_markdup"
"logs/samtools_markdup"
"benchmarks/samtools_index_post_filter"
"logs/samtools_index_post_filter"
"benchmarks/samtools_index/post_markdup"
"logs/samtools_index/post_markdup"
"benchmarks/samtools_index"
"logs/samtools_index"
"benchmarks/remove_mito_reads"
"logs/remove_mito_reads"
"benchmarks/qualimap"
"logs/qualimap"
"benchmarks/preseq"
"logs/preseq"
"benchmarks/picard/CollectInsertSizeMetrics"
"logs/picard/CollectInsertSizeMetrics"
"benchmarks/picard/CollectAlignmentSummaryMetrics"
"logs/picard/CollectAlignmentSummaryMetrics"
"benchmarks/phantompeakqualtools"
"logs/phantompeakqualtools"
"benchmarks/peak_annotation"
"logs/peak_annotation"
"benchmarks/normalized_coverage"
"logs/normalized_coverage"
"logs/multiqc"
"benchmarks/multiqc"
"logs/motif_analysis"
"benchmarks/motif_analysis"
"benchmarks/macs2"
"logs/macs2"
"benchmarks/heatmap"
"logs/heatmap/matrix"
"logs/heatmap/plot"
"benchmarks/frip"
"logs/frip"
"benchmarks/fragment_size_analysis"
"logs/fragment_size_analysis"
"benchmarks/fastqc"
"logs/fastqc"
"benchmarks/fastp"
"logs/fastp"
"benchmarks/correlation_analysis"
"logs/correlation_analysis"
"benchmarks/mitoATAC_calculate"
"logs/mitoATAC_calculate"
"benchmarks/bowtie2"
"logs/bowtie2"
"benchmarks/blacklist_region_filter"
"logs/blacklist_region_filter"
"benchmarks/bigwig"
"logs/bigwig"
)


for dir in "${dirs[@]}"; do 
  echo "Creating directory: ${dir}"
  mkdir -p "$dir"
  if [$? -e 0 ]; then
      echo "Successfully Created directory: ${dir}"
  fi 
done

echo "Task of creating directories succesful"

